baseURL = "https://gitpaco.github.io/hPrueba/"
languageCode = "es"
title = "Título/logo del sítio"
theme = "tale"

[Author]
  name="Creado por FFdev"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    title = "contacto"
    url = "/contacto/"
    weigth = 0
  [[menu.main]]
    identifier = "logopedia"
    name = "Logopedia"
    title = "Logopedia"
    url = "/logopedia/"
    weight = 0
  [[menu.main]]
    identifier = "primaria"
    name = "Primaria"
    title = "primaria"
    url = "/primaria/"
    weigth = 0

[params]
  css= ["css/estilos.css"]
